[WinEventLog://Application]
index = soc_windows

[WinEventLog://Security]
index = soc_windows

[WinEventLog://System]
index = soc_windows

[WinEventLog://Microsoft-Windows-Sysmon/Operational]
disabled = 0
start_from = oldest
current_only = 0
checkpointInterval = 5
renderXml = true
index = soc_windows
source = XmlWinEventLog:Microsoft-Windows-Sysmon/Operational

[WinEventLog://Microsoft-Windows-PowerShell/Operational]
disabled = 0
start_from = oldest
current_only = 0
checkpointInterval = 5
renderXml = true
index = soc_windows
source = XmlWinEventLog:Microsoft-Windows-PowerShell/Operational
